services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: delivery
    command: >
      --slow_query_log=ON --long_query_time=0.1
      --slow_query_log_file=/var/log/mysql/slow.log
      --performance_schema=ON
      --innodb_buffer_pool_size=2G
    ports: ["3306:3306"]
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql/log:/var/log/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  mysql-data:
